server:
  port: 8802
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: service-feign
# 配置熔断器
feign:
  hystrix:
    enabled: true

